version: '2'
services:
    application-app:
        image: application
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://application-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    application-mssql:
        extends:
            file: mssql.yml
            service: application-mssql
